name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  check:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-python.yml@main

  docker:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-docker.yml@main
    # The build context needs a locally cached Tizen installer that is not stored in Git.
    with:
      context: ./src/tizen_tool/resources
      file: ./src/tizen_tool/resources/Dockerfile
      build: false
