name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: make install_deps
      - uses: actions/cache@v5
        with:
          path: ~/.cache/prek
          key: prek|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            prek|${{ runner.os }}|
      - uses: j178/prek-action@v2
        with:
          extra_args: --all-files --hook-stage pre-commit

  release:
    needs: check
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/tizen-tool
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: make install_deps
      - run: make build
      - uses: pypa/gh-action-pypi-publish@release/v1
      - uses: loopwerk/tag-changelog@v1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changes }}
